//
// Created by raman.chakhouski on 3/24/2023.
//

#ifndef EXCESSIVE_DEBUGBYTECODEPRINTER_H
#define EXCESSIVE_DEBUGBYTECODEPRINTER_H

#include <ios>
#include "Model/ConstantPool.h"


namespace DebugBytecodePrinter
{
    struct CDebugPrinterContext
    {
        std::ostream& stream;
        std::shared_ptr<Compiler::CConstantPool> ConstantPool;
    };

#define DECLARE_OPCODE_PRINTER(_Opcode) void Print_##_Opcode(const CDebugPrinterContext& Context);
    
    // 0 - 9
    DECLARE_OPCODE_PRINTER(NOP)
    DECLARE_OPCODE_PRINTER(ACONST_NULL)
    DECLARE_OPCODE_PRINTER(ICONST_M1)
    DECLARE_OPCODE_PRINTER(ICONST_0)
    DECLARE_OPCODE_PRINTER(ICONST_1)
    DECLARE_OPCODE_PRINTER(ICONST_2)
    DECLARE_OPCODE_PRINTER(ICONST_3)
    DECLARE_OPCODE_PRINTER(ICONST_4)
    DECLARE_OPCODE_PRINTER(ICONST_5)
    DECLARE_OPCODE_PRINTER(LCONST_0)

    // 10 - 19
    DECLARE_OPCODE_PRINTER(LCONST_1)
    DECLARE_OPCODE_PRINTER(FCONST_0)
    DECLARE_OPCODE_PRINTER(FCONST_1)
    DECLARE_OPCODE_PRINTER(FCONST_2)
    DECLARE_OPCODE_PRINTER(DCONST_0)
    DECLARE_OPCODE_PRINTER(DCONST_1)
    DECLARE_OPCODE_PRINTER(BIPUSH)
    DECLARE_OPCODE_PRINTER(SIPUSH)
    DECLARE_OPCODE_PRINTER(LDC)
    DECLARE_OPCODE_PRINTER(LDC_W)

    // 20 - 29
    DECLARE_OPCODE_PRINTER(LDC2_W)
    DECLARE_OPCODE_PRINTER(ILOAD)
    DECLARE_OPCODE_PRINTER(LLOAD)
    DECLARE_OPCODE_PRINTER(FLOAD)
    DECLARE_OPCODE_PRINTER(DLOAD)
    DECLARE_OPCODE_PRINTER(ALOAD)
    DECLARE_OPCODE_PRINTER(ILOAD_0)
    DECLARE_OPCODE_PRINTER(ILOAD_1)
    DECLARE_OPCODE_PRINTER(ILOAD_2)
    DECLARE_OPCODE_PRINTER(ILOAD_3)

    // 30 - 39
    DECLARE_OPCODE_PRINTER(LLOAD_0)
    DECLARE_OPCODE_PRINTER(LLOAD_1)
    DECLARE_OPCODE_PRINTER(LLOAD_2)
    DECLARE_OPCODE_PRINTER(LLOAD_3)
    DECLARE_OPCODE_PRINTER(FLOAD_0)
    DECLARE_OPCODE_PRINTER(FLOAD_1)
    DECLARE_OPCODE_PRINTER(FLOAD_2)
    DECLARE_OPCODE_PRINTER(FLOAD_3)
    DECLARE_OPCODE_PRINTER(DLOAD_0)
    DECLARE_OPCODE_PRINTER(DLOAD_1)

    // 40 - 49
    DECLARE_OPCODE_PRINTER(DLOAD_2)
    DECLARE_OPCODE_PRINTER(DLOAD_3)
    DECLARE_OPCODE_PRINTER(ALOAD_0)
    DECLARE_OPCODE_PRINTER(ALOAD_1)
    DECLARE_OPCODE_PRINTER(ALOAD_2)
    DECLARE_OPCODE_PRINTER(ALOAD_3)
    DECLARE_OPCODE_PRINTER(IALOAD)
    DECLARE_OPCODE_PRINTER(LALOAD)
    DECLARE_OPCODE_PRINTER(FALOAD)
    DECLARE_OPCODE_PRINTER(DALOAD)

    // 50 - 59
    DECLARE_OPCODE_PRINTER(AALOAD)
    DECLARE_OPCODE_PRINTER(BALOAD)
    DECLARE_OPCODE_PRINTER(CALOAD)
    DECLARE_OPCODE_PRINTER(SALOAD)
    DECLARE_OPCODE_PRINTER(ISTORE)
    DECLARE_OPCODE_PRINTER(LSTORE)
    DECLARE_OPCODE_PRINTER(FSTORE)
    DECLARE_OPCODE_PRINTER(DSTORE)
    DECLARE_OPCODE_PRINTER(ASTORE)
    DECLARE_OPCODE_PRINTER(ISTORE_0)

    // 60 - 69
    DECLARE_OPCODE_PRINTER(ISTORE_1)
    DECLARE_OPCODE_PRINTER(ISTORE_2)
    DECLARE_OPCODE_PRINTER(ISTORE_3)
    DECLARE_OPCODE_PRINTER(LSTORE_0)
    DECLARE_OPCODE_PRINTER(LSTORE_1)
    DECLARE_OPCODE_PRINTER(LSTORE_2)
    DECLARE_OPCODE_PRINTER(LSTORE_3)
    DECLARE_OPCODE_PRINTER(FSTORE_0)
    DECLARE_OPCODE_PRINTER(FSTORE_1)
    DECLARE_OPCODE_PRINTER(FSTORE_2)

    // 70 - 79
    DECLARE_OPCODE_PRINTER(FSTORE_3)
    DECLARE_OPCODE_PRINTER(DSTORE_0)
    DECLARE_OPCODE_PRINTER(DSTORE_1)
    DECLARE_OPCODE_PRINTER(DSTORE_2)
    DECLARE_OPCODE_PRINTER(DSTORE_3)
    DECLARE_OPCODE_PRINTER(ASTORE_0)
    DECLARE_OPCODE_PRINTER(ASTORE_1)
    DECLARE_OPCODE_PRINTER(ASTORE_2)
    DECLARE_OPCODE_PRINTER(ASTORE_3)
    DECLARE_OPCODE_PRINTER(IASTORE)

    // 80 - 89
    DECLARE_OPCODE_PRINTER(LASTORE)
    DECLARE_OPCODE_PRINTER(FASTORE)
    DECLARE_OPCODE_PRINTER(DASTORE)
    DECLARE_OPCODE_PRINTER(AASTORE)
    DECLARE_OPCODE_PRINTER(BASTORE)
    DECLARE_OPCODE_PRINTER(CASTORE)
    DECLARE_OPCODE_PRINTER(SASTORE)
    DECLARE_OPCODE_PRINTER(POP)
    DECLARE_OPCODE_PRINTER(POP2)
    DECLARE_OPCODE_PRINTER(DUP)

    // 90 - 99
    DECLARE_OPCODE_PRINTER(DUP_X1)
    DECLARE_OPCODE_PRINTER(DUP_X2)
    DECLARE_OPCODE_PRINTER(DUP2)
    DECLARE_OPCODE_PRINTER(DUP2_X1)
    DECLARE_OPCODE_PRINTER(DUP2_X2)
    DECLARE_OPCODE_PRINTER(SWAP)
    DECLARE_OPCODE_PRINTER(IADD)
    DECLARE_OPCODE_PRINTER(LADD)
    DECLARE_OPCODE_PRINTER(FADD)
    DECLARE_OPCODE_PRINTER(DADD)

    // 100 - 109
    DECLARE_OPCODE_PRINTER(ISUB)
    DECLARE_OPCODE_PRINTER(LSUB)
    DECLARE_OPCODE_PRINTER(FSUB)
    DECLARE_OPCODE_PRINTER(DSUB)
    DECLARE_OPCODE_PRINTER(IMUL)
    DECLARE_OPCODE_PRINTER(LMUL)
    DECLARE_OPCODE_PRINTER(FMUL)
    DECLARE_OPCODE_PRINTER(DMUL)
    DECLARE_OPCODE_PRINTER(IDIV)
    DECLARE_OPCODE_PRINTER(LDIV)

    // 110 - 119
    DECLARE_OPCODE_PRINTER(FDIV)
    DECLARE_OPCODE_PRINTER(DDIV)
    DECLARE_OPCODE_PRINTER(IREM)
    DECLARE_OPCODE_PRINTER(LREM)
    DECLARE_OPCODE_PRINTER(FREM)
    DECLARE_OPCODE_PRINTER(DREM)
    DECLARE_OPCODE_PRINTER(INEG)
    DECLARE_OPCODE_PRINTER(LNEG)
    DECLARE_OPCODE_PRINTER(FNEG)
    DECLARE_OPCODE_PRINTER(DNEG)

    // 120 - 129
    DECLARE_OPCODE_PRINTER(ISHL)
    DECLARE_OPCODE_PRINTER(LSHL)
    DECLARE_OPCODE_PRINTER(ISHR)
    DECLARE_OPCODE_PRINTER(LSHR)
    DECLARE_OPCODE_PRINTER(IUSHR)
    DECLARE_OPCODE_PRINTER(LUSHR)
    DECLARE_OPCODE_PRINTER(IAND)
    DECLARE_OPCODE_PRINTER(LAND)
    DECLARE_OPCODE_PRINTER(IOR)
    DECLARE_OPCODE_PRINTER(LOR)

    // 130 - 139
    DECLARE_OPCODE_PRINTER(IXOR)
    DECLARE_OPCODE_PRINTER(LXOR)
    DECLARE_OPCODE_PRINTER(IINC)
    DECLARE_OPCODE_PRINTER(I2L)
    DECLARE_OPCODE_PRINTER(I2F)
    DECLARE_OPCODE_PRINTER(I2D)
    DECLARE_OPCODE_PRINTER(L2I)
    DECLARE_OPCODE_PRINTER(L2F)
    DECLARE_OPCODE_PRINTER(L2D)
    DECLARE_OPCODE_PRINTER(F2I)

    // 140 - 149
    DECLARE_OPCODE_PRINTER(F2L)
    DECLARE_OPCODE_PRINTER(F2D)
    DECLARE_OPCODE_PRINTER(D2I)
    DECLARE_OPCODE_PRINTER(D2L)
    DECLARE_OPCODE_PRINTER(D2F)
    DECLARE_OPCODE_PRINTER(I2B)
    DECLARE_OPCODE_PRINTER(I2C)
    DECLARE_OPCODE_PRINTER(I2S)
    DECLARE_OPCODE_PRINTER(LCMP)
    DECLARE_OPCODE_PRINTER(FCMPL)

    // 150 - 159
    DECLARE_OPCODE_PRINTER(FCMPG)
    DECLARE_OPCODE_PRINTER(DCMPL)
    DECLARE_OPCODE_PRINTER(DCMPG)
    DECLARE_OPCODE_PRINTER(IFEQ)
    DECLARE_OPCODE_PRINTER(IFNE)
    DECLARE_OPCODE_PRINTER(IFLT)
    DECLARE_OPCODE_PRINTER(IFGE)
    DECLARE_OPCODE_PRINTER(IFGT)
    DECLARE_OPCODE_PRINTER(IFLE)
    DECLARE_OPCODE_PRINTER(IF_ICMPEQ)

    // 160 - 169
    DECLARE_OPCODE_PRINTER(IF_ICMPNE)
    DECLARE_OPCODE_PRINTER(IF_ICMPLT)
    DECLARE_OPCODE_PRINTER(IF_ICMPGE)
    DECLARE_OPCODE_PRINTER(IF_ICMPGT)
    DECLARE_OPCODE_PRINTER(IF_ICMPLE)
    DECLARE_OPCODE_PRINTER(IF_ACMPEQ)
    DECLARE_OPCODE_PRINTER(IF_ACMPNE)
    DECLARE_OPCODE_PRINTER(GOTO)
    DECLARE_OPCODE_PRINTER(JSR)
    DECLARE_OPCODE_PRINTER(RET)

    // 170 - 179
    DECLARE_OPCODE_PRINTER(TABLESWITCH)
    DECLARE_OPCODE_PRINTER(LOOKUPSWITCH)
    DECLARE_OPCODE_PRINTER(IRETURN)
    DECLARE_OPCODE_PRINTER(LRETURN)
    DECLARE_OPCODE_PRINTER(FRETURN)
    DECLARE_OPCODE_PRINTER(DRETURN)
    DECLARE_OPCODE_PRINTER(ARETURN)
    DECLARE_OPCODE_PRINTER(RETURN)
    DECLARE_OPCODE_PRINTER(GETSTATIC)
    DECLARE_OPCODE_PRINTER(PUTSTATIC)

    // 180 - 189
    DECLARE_OPCODE_PRINTER(GETFIELD)
    DECLARE_OPCODE_PRINTER(PUTFIELD)
    DECLARE_OPCODE_PRINTER(INVOKEVIRTUAL)
    DECLARE_OPCODE_PRINTER(INVOKESPECIAL)
    DECLARE_OPCODE_PRINTER(INVOKESTATIC)
    DECLARE_OPCODE_PRINTER(INVOKEINTERFACE)
    DECLARE_OPCODE_PRINTER(INVOKEDYNAMIC)
    DECLARE_OPCODE_PRINTER(NEW)
    DECLARE_OPCODE_PRINTER(NEWARRAY)
    DECLARE_OPCODE_PRINTER(ANEWARRAY)

    // 190 - 199
    DECLARE_OPCODE_PRINTER(ARRAYLENGTH)
    DECLARE_OPCODE_PRINTER(ATHROW)
    DECLARE_OPCODE_PRINTER(CHECKCAST)
    DECLARE_OPCODE_PRINTER(INSTANCEOF)
    DECLARE_OPCODE_PRINTER(MONITORENTER)
    DECLARE_OPCODE_PRINTER(MONITOREXIT)
    DECLARE_OPCODE_PRINTER(WIDE)
    DECLARE_OPCODE_PRINTER(MULTIANEWARRAY)
    DECLARE_OPCODE_PRINTER(IFNULL)
    DECLARE_OPCODE_PRINTER(IFNONNULL)

    // 200 - 201
    DECLARE_OPCODE_PRINTER(GOTO_W)
    DECLARE_OPCODE_PRINTER(JSR_W)

#undef DECLARE_OPCODE_PRINTER;
};


#endif //EXCESSIVE_DEBUGBYTECODEPRINTER_H
